# Generated by Django 4.2.6 on 2023-11-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('card', 'card'), ('cash', 'cash')], default='cash', max_length=15),
        ),
    ]
