# Generated by Django 4.2.6 on 2023-11-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodel',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[(' CARD ', ' CARD '), (' CASH ', ' CASH ')], default='cash', max_length=10),
        ),
    ]
