# Generated by Django 4.2.7 on 2023-11-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_alter_phonemodel_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodel',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
